# -*- coding: utf-8 -*-
"""ScientificCalculator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10aIPsIwIdsEe5y3rP-9h5-UOx3iTzSkK
"""

import numpy as np

def basic_operations():
    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))

    print("\nBasic Operations:")
    print(f"Addition: {num1} + {num2} = {num1 + num2}")
    print(f"Subtraction: {num1} - {num2} = {num1 - num2}")
    print(f"Multiplication: {num1} * {num2} = {num1 * num2}")
    if num2 != 0:
        print(f"Division: {num1} / {num2} = {num1 / num2}")
    else:
        print("Error! Division by zero.")

def trigonometric_operations():
    angle = float(input("Enter the angle in radians: "))

    print("\nTrigonometric Functions:")
    print(f"Sine (sin): sin({angle}) = {np.sin(angle)}")
    print(f"Cosine (cos): cos({angle}) = {np.cos(angle)}")
    print(f"Tangent (tan): tan({angle}) = {np.tan(angle)}")

def logarithmic_operations():
    num = float(input("Enter the number for logarithm (natural log): "))

    if num > 0:
        print(f"\nLogarithm: log({num}) = {np.log(num)}")
    else:
        print("Error! Logarithm of non-positive numbers is undefined.")

def statistical_operations():
    numbers = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))

    print("\nStatistical Functions:")
    print(f"Mean: {np.mean(numbers)}")
    print(f"Median: {np.median(numbers)}")
    print(f"Standard Deviation: {np.std(numbers)}")

def scientific_calculator():
    print("Welcome to the Scientific Calculator!")
    print("1. Basic Operations (+, -, *, /)")
    print("2. Trigonometric Functions (sin, cos, tan)")
    print("3. Logarithmic Functions (log)")
    print("4. Statistical Functions (mean, median, std)")
    print("Type 'exit' to quit")

    while True:
        choice = input("\nChoose an operation (or type 'exit' to quit): ").lower()

        if choice == 'exit':
            print("Exiting the calculator. Goodbye!")
            break

        elif choice == '1':
            basic_operations()

        elif choice == '2':
            trigonometric_operations()

        elif choice == '3':
            logarithmic_operations()

        elif choice == '4':
            statistical_operations()

        else:
            print("Invalid choice. Please select a valid operation.")

# Run the scientific calculator
scientific_calculator()